### ISSUE TITLE
Find Resources for Mobile Notification

### ISSUE THREAD

**Issue by sarveshbhatnagar** [sarveshbhatnagar/userportal-backend#46]
Find Resources we can use for mobile notification. -> Pratyash

**Comment by sarveshbhatnagar** [comment]
Acceptance Criteria : Google Doc for learning

**Comment by Pratyashshrivastava** [comment]
Using AWS SNS ( Simple Notification Services) we can send push notification in remote mobile.
refer to : 
https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/sns-examples.html
